---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
  namespace: bugfixes
  labels:
    name: agent-service
spec:
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: agent-service
          image: ghcr.io/bugfixes/agent-service:0.1.5
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token-agent-service
                  key: token

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: bugfixes
  name: agent-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: acme-prod
  labels:
    app: agent-service
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.bugfixes.dev
      secretName: bugfixes-dev-tls
  rules:
    - host: api.bugfixes.dev
      http:
        paths:
          - path: /agent
            pathType: Prefix
            backend:
              service:
                name: agent-service
                port:
                  number: 3000
